// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0
// source: misc.sql

package database

import (
	"context"
)

const getLastInsertID = `-- name: GetLastInsertID :one
SELECT LAST_INSERT_ID()
`

func (q *Queries) GetLastInsertID(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, getLastInsertID)
	var last_insert_id int64
	err := row.Scan(&last_insert_id)
	return last_insert_id, err
}
