// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0

package database

import (
	"database/sql"
	"time"
)

type Ingredient struct {
	ID          int64
	CreatedAt   time.Time
	UpdatedAt   time.Time
	Name        string
	Description sql.NullString
}

type Recipe struct {
	ID          int64
	CreatedAt   time.Time
	UpdatedAt   time.Time
	Name        string
	Description sql.NullString
	Url         sql.NullString
	PrepTime    sql.NullString
	CookTime    sql.NullString
	TotalTime   sql.NullString
}

type RecipeIngredient struct {
	ID           int64
	CreatedAt    time.Time
	UpdatedAt    time.Time
	IngredientID string
	RecipeID     string
	Quantity     int32
	Units        string
}
