// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0
// source: recipes.sql

package database

import (
	"context"
	"database/sql"
	"time"
)

const createRecipe = `-- name: CreateRecipe :execresult
INSERT INTO recipes(created_at, updated_at, name, description, url, prep_time, cook_time, total_time, owner_id)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateRecipeParams struct {
	CreatedAt   time.Time
	UpdatedAt   time.Time
	Name        string
	Description sql.NullString
	Url         sql.NullString
	PrepTime    sql.NullString
	CookTime    sql.NullString
	TotalTime   sql.NullString
	OwnerID     int64
}

func (q *Queries) CreateRecipe(ctx context.Context, arg CreateRecipeParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createRecipe,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.Name,
		arg.Description,
		arg.Url,
		arg.PrepTime,
		arg.CookTime,
		arg.TotalTime,
		arg.OwnerID,
	)
}

const getRecipe = `-- name: GetRecipe :one
SELECT id, created_at, updated_at, name, description, url, prep_time, cook_time, total_time, owner_id FROM recipes
WHERE id = ?
`

func (q *Queries) GetRecipe(ctx context.Context, id int64) (Recipe, error) {
	row := q.db.QueryRowContext(ctx, getRecipe, id)
	var i Recipe
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.Description,
		&i.Url,
		&i.PrepTime,
		&i.CookTime,
		&i.TotalTime,
		&i.OwnerID,
	)
	return i, err
}

const getRecipesForUser = `-- name: GetRecipesForUser :many
SELECT id, created_at, updated_at, name, description, url, prep_time, cook_time, total_time, owner_id FROM recipes
WHERE owner_id = ?
`

func (q *Queries) GetRecipesForUser(ctx context.Context, ownerID int64) ([]Recipe, error) {
	rows, err := q.db.QueryContext(ctx, getRecipesForUser, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Recipe
	for rows.Next() {
		var i Recipe
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Name,
			&i.Description,
			&i.Url,
			&i.PrepTime,
			&i.CookTime,
			&i.TotalTime,
			&i.OwnerID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
